### ISSUE TITLE
Please bring back commit history

### ISSUE THREAD

**Issue by snird** [TryGhost/Themes#134]
Basically the same as this: https://github.com/TryGhost/Ease/issues/28
But here for visibility, I guess. And it's relevant to other themes too

**Comment by ErisDS** [comment]
Hey @snird we're working on a plan for if/how we can do this. We'll update when we know if it's possible.

**Comment by minimaluminium** [comment]
Hey @snird. We finished merging the old commit history to the monorepo. Now all our themes including Ease got their history back.

**Comment by snird** [comment]
> Hey @snird. We finished merging the old commit history to the monorepo. Now all our themes including Ease got their history back.

You guys are amazing. Thank you!
