### ISSUE TITLE
[Dawn] Missing dark theme change button

### ISSUE THREAD

**Issue by spirosag** [TryGhost/Themes#136]
There used to be a button at the bottom of the page to change the theme to dark/light. Now there's no such option. I believe it was removed with the addition of the "auto" setting for the theme. Is there any change to get it back? Now the reader can't override the setting.

**Comment by minimaluminium** [comment]
Hey everyone! We've made some discussion on this and decided not to bring back the toggle for the following reasons.

* There's an `Auto` mode which already gives readers an option to change their preference
* We're standardizing and making global elements like header and footer to be consistent across official themes and this won't work with this well
* The header has already enough items like nav links, dropdown toggle, search icon and subscribe links. We wouldn't want to clutter the header

If anyone wants to bring back the toggle, [here's](https://github.com/TryGhost/Dawn/commit/6035107fc486a766b05cfbb73928f16cadc4124d) the commit that removed the feature. You'll be able to see the changes and have to play with the theme code a bit.
