### ISSUE TITLE
[Ease] Sticky table of Content

### ISSUE THREAD

**Issue by chisarie** [TryGhost/Themes#137]
Hello and thank you very much for this nice theme.

I would love to able to add to this theme a "sticky" table of content, as explained in this tutorial: https://ghost.org/docs/tutorials/adding-a-table-of-contents/
Unfortunately I was not able to get it running by following the steps in the tutorial: my table of content is placed on the left of the page and it does not stick on top of the page when scrolling. Do you have any suggestions to make this work with the Ease template?

Thank you very much in advance for the help.

**Comment by minimaluminium** [comment]
Hey @chisarie, sorry about the very long delay. Just wanted to let you know that the tutorial has been updated with new instructions. Would you be able to try the new instructions?

Also our [forum](https://forum.ghost.org) is a great place to ask for this kind of support.
