### ISSUE TITLE
[Journal] Card of the latest post does not respect which collection it is in.

### ISSUE THREAD

**Issue by mehmetalianil** [TryGhost/Themes#138]
If we have two collections, say letters and blog, and have internal tags for each, the template renders the card for the latest post irrespective of the collection it is of. 

Following this logic, the template skips the first post of the collection, assuming that it will be displayed as the first post. 

Here, for example, this is the index page of the collection letters, but the latest post displayed is from the collection blog.
The posts of the collection letters are nor displayed, since only post in there is skipped, assuming that it is displayed as the latest post. 
![image](https://user-images.githubusercontent.com/551129/177362662-26379c98-8661-4eb2-9f32-5296df09e4ac.png)

**Comment by minimaluminium** [comment]
Hey @mehmetalianil, thanks for the report! This is fixed. The latest post is displayed depending on what collection it's in.
