### ISSUE TITLE
[Edge] Minor JS bugs

### ISSUE THREAD

**Issue by brvnnghi** [TryGhost/Themes#142]
Hello,

I'd like to report following bugs regarding the newly updated theme:

1. Screenshot 1: In pages (not posts), which do not have feed, "imagesLoaded" still being called.
2. Screenshot 2: Pagination errors on Tag page.
3. Screenshot 3: console.log() left-over in production.

These are found on the official demo theme:
https://edge.ghost.io

Great themes, with so many breaking changes introduced in this version (for ex, removing Grid CSS and Social Icon CSS, change some important body class name...). Those who use GitHub action to modify this theme should aware.

Thanks.

<img width="1081" alt="Screen Shot 2022-07-26 at 19 22 26" src="https://user-images.githubusercontent.com/79747550/181005247-82f973ab-a07b-46b8-aec7-8d020c2f4067.png">

<img width="1077" alt="Screen Shot 2022-07-26 at 19 22 11" src="https://user-images.githubusercontent.com/79747550/181005357-e0c3db19-48db-4c9a-b04c-c0542a8eb528.png">

<img width="651" alt="Screen Shot 2022-07-26 at 19 21 29" src="https://user-images.githubusercontent.com/79747550/181004958-e883aa8c-1487-4c52-a5b9-dfb6fdf4ade6.png">

**Comment by minimaluminium** [comment]
Hey @brvnnghi, we really appreciate your detailed feedbacks. All these errors are fixed now, make sure re-install the theme to get the update.

**Comment by brvnnghi** [comment]
> Hey @brvnnghi, we really appreciate your detailed feedbacks. All these errors are fixed now, make sure re-install the theme to get the update.

Thanks for these fixes. However, there is another bug found here:
![img 4](https://user-images.githubusercontent.com/79747550/195373610-27ee7ccd-b157-4c26-94c6-8db4696767af.jpg)

I've found it while updating your theme into my GitHub action.

Also, please check the "yarn dev" process (gulpfile.js), which generates a different "main.min.js" than the one in your commit. I have inspected the difference, and found no "loadNextPage()" function, which has been recently added.

Hope it helps.

**Comment by minimaluminium** [comment]
Hey @brvnnghi, sorry about the issues! The error is now fixed, and you should now have the same minified JS file when you run `yarn dev`.
