### ISSUE TITLE
[Edge] They stack and juxtapose the images [Incorrect loading of images on the home screen]

### ISSUE THREAD

**Issue by khalil-i-o** [TryGhost/Themes#143]
Images don't seem to load as they should and freeze. Achieving a juxtaposition.

Cleared cache, switched browsers to PC, Chrome, etc.. The result is the same. However, it is random, sometimes it happens and sometimes it doesn't; it is more noticeable when you have more images.

This happens on the self-hosted blog, but I also noticed it happens on as in: https://edge.ghost.io/

Here I attach video and screenshot: 

https://user-images.githubusercontent.com/68512577/180103267-f3fc8779-3337-4a4c-941e-ea7b044da560.mp4

![IMG_20220720_201018_491](https://user-images.githubusercontent.com/68512577/180103251-ab937fb5-51f1-4f90-8714-4056e6740990.jpg)

**Comment by GoOz** [comment]
Got the same behaviour. It doesn't seem to happen if you scroll slowy though.

**Comment by minimaluminium** [comment]
We're aware of this issue and will be fixed in the near future.

**Comment by minimaluminium** [comment]
Hey everyone! This is now fixed, make sure re-install the theme to get the fixes.
