### ISSUE TITLE
[Edge] Additional posts with edge theme

### ISSUE THREAD

**Issue by orangesurf** [TryGhost/Themes#146]
There are more tiles in the homepage than posts, meaning some are repeated multiple times. How can I disable this so that there is only a single tile per post?

Thank you for this nice theme.

![image](https://user-images.githubusercontent.com/91332210/185800559-1a585fce-b998-457e-991b-12b3b193cfe5.png)

**Comment by GoOz** [comment]
Got the same issue here, not as many duplicates, but still.

**Comment by minimaluminium** [comment]
We're aware of this issue and will be fixed in the near future.

**Comment by minimaluminium** [comment]
Hey everyone, thanks for the feedbacks! This is now fixed, make sure re-install the theme to get the fixes applied.
