### ISSUE TITLE
Solo: How do I paginate my posts?

### ISSUE THREAD

**Issue by twhite96** [TryGhost/Themes#168]
I have over 300 articles on my blog and the infinite scrolling is an awful UX decision. How can I fix this?

**Comment by minimaluminium** [comment]
Hey @twhite96, you'd have to add a little bit of customization to the theme to have a different pagination behavior. For example, you can do as following to add a button to load more posts.

1. Add a button in `index.hbs` right after the `.gh-feed` closing tag [here](https://github.com/TryGhost/Solo/blob/dd19e4a0d70d2190ba430fef73520033ef8fefc3/index.hbs#L53).

``` html
<button class="gh-loadmore gh-btn" style="display: flex; margin: 64px auto 0;">Load more</button>
```

Note that it should also be added to `tag.hbs` and `author.hbs` as well if you want the same for these pages. A bit of CSS was added as inline attribute for the simplicity. You can move the CSS somewhere if you want to.

2. Change the first parameter value to `false` in the pagination function [here](https://github.com/TryGhost/Solo/blob/dd19e4a0d70d2190ba430fef73520033ef8fefc3/assets/js/main.js#L53).

We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
