### ISSUE TITLE
 [Alto] Huge layout shift when using featured posts.

### ISSUE THREAD

**Issue by Spark1y** [TryGhost/Themes#169]
When using this Alto theme with the featured posts function, looks like the site-content element is loaded first then the featured post element, which leads to a huge layout shift and case a bad user experience, this also occurred in the [alto.ghost.io](https://alto.ghost.io), hope this should be resolved.

**Comment by minimaluminium** [comment]
Hey @Spark1y, this is now fixed. The featured posts carousel shouldn't be causing any layout shift problem anymore. Make sure re-install the theme to get the update.
