### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by clementduveau** [TryGhost/Themes#174]
Hello,

Lack of i18n support cut you out of businesses in a lot of places. Considering the effort made to standardize the officials themes, most of the content can be internationalized easily.

Will you accept contributions in the near future for i18n on official themes ? How could I make PR on some themes ?

Thank you

**Comment by minimaluminium** [comment]
Hello @clementduveau,

You're very welcome to translate any theme or release your own translated themes! We're not ready to include translations by default in our official themes at the moment.

**Comment by filipesmedeiros** [comment]
Just to understand: none of the themes developed by the Ghost team use the [official translating API and guide for Ghost themes](https://ghost.org/docs/themes/helpers/translate/)? Thanks for all the work :)
