### ISSUE TITLE
[Wave] Player broken on index page after redesign

### ISSUE THREAD

**Issue by campwx** [TryGhost/Themes#180]
After the redesign, the player no longer works on the index page. Nothing happens when clicking any of the play episode buttons from the index page, although it does work if you are within a specific post page. It used to show a web player at the bottom of the screen.

To recreate, just head to the official Wave theme at https://wave.ghost.io/ and try clicking any of the play buttons from the main landing page.

**Comment by minimaluminium** [comment]
Hey @campwx, the homepage player is now back. Make sure re-install the theme to get the updates.
