### ISSUE TITLE
[Wave] Player missing all playback buttons

### ISSUE THREAD

**Issue by campwx** [TryGhost/Themes#181]
The player used to have skip back, skip forward, and playback speed, which were critical to a useable media player for podcast content. Not sure if this is just a bug, but post-redesign, those buttons are all gone.

Since there is no way to click forward or backwards in the player to jump to a different time, those button were the only way listeners had to navigate an episode. Without the buttons, the player is basically unusable, which kind of defeats the purpose of the Wave theme.

**Comment by minimaluminium** [comment]
Hey @campwx, the player buttons are now back. Make sure re-install the theme to get the updates.
