### ISSUE TITLE
[Dawn] logo in dark mode don't change

### ISSUE THREAD

**Issue by simepy** [TryGhost/Themes#190]
Hello,
Thank you for your work in all the themes.

I don't see a other issue related to this so I submit this one

I switch to dark mode with the white logo upload, the logo is not loaded during the dark mode.

This is the logo for white mode: 
![image](https://user-images.githubusercontent.com/12037541/201445291-67378e34-68d6-44fc-a620-ce8274b71f82.png)

This is the logo for dark mode:
![image](https://user-images.githubusercontent.com/12037541/201445367-92c261dd-ce2b-4a56-8763-7864b4f090f8.png)

The two logo is well loaded here:
![image](https://user-images.githubusercontent.com/12037541/201445613-48a0f3ff-9f7f-4e44-819c-691782973b5b.png)
Note: I also have the issue if I force color scheme to `Dark`

I updated to the latest Draw theme available on the design page
I used Firefox but I also have the issue on Chrome

Any though is welcome
Have a nice day / evening

**Comment by minimaluminium** [comment]
Hi @simepy, thanks for your kind words :)

The dark mode logo issue is now fixed in https://github.com/TryGhost/Themes/commit/9da0896ab719dfbccee0227bbc59b88c0d2ee524. Make sure to re-install the theme to get the fixes applied on your site. Thanks again for your well detailed feedback.
