### ISSUE TITLE
[Dope] Option to direct link to a page

### ISSUE THREAD

**Issue by BurgerhoutJ** [TryGhost/Themes#195]
Hi,

Is it possible from the homepage, if you click on a topic/tag, that it opens a page directly instead of a page with the relevant blog posts?
I just want 3 or 4 pages with the relevant information and not an overview of all the blog posts with that specific tag.

**Comment by minimaluminium** [comment]
Hey @BurgerhoutJ, this can be accomplished with some customization in `index.hbs` of the theme [here](https://github.com/TryGhost/Dope/blob/25f4a1a16afb3c4ce71f15f9d8366617843201a1/index.hbs#L6-L23).

```hbs
{{#get "pages" limit="all"}}
<div class="tag-feed owl" data-count="{{pagination.total}}">

    {{#foreach pages}}
    <div class="tag u-placeholder">
        <img class="tag-image u-object-fit" src="{{#if feature_image}}{{img_url feature_image}}{{else}}{{@site.cover_image}}{{/if}}" alt="{{name}}">
        <div class="tag-content">
            <h2 class="tag-name">{{title}}</h2>

            {{#if excerpt}}
                <div class="tag-description">
                    {{excerpt}}
                </div>
            {{/if}}
        </div>
        <a class="u-permalink" href="{{url}}"></a>
    </div>
    {{/foreach}}

</div>
{{/get}}
```

We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
