### ISSUE TITLE
[Dawn] Option to show publication cover on homepage

### ISSUE THREAD

**Issue by os72** [TryGhost/Themes#196]
[Dawn] Option to show publication cover on homepage - instead of icon
This would look quite similar with Edition with cover image at half screen (perhaps less, 1/3 screen?)

**Comment by minimaluminium** [comment]
Hey @os72, if you need cover image support, Edition should be the right choice. It also has an option to set the cover image height to half screen which works out of the box without requiring any customization.

**Comment by minimaluminium** [comment]
> But it has that direct free subscription button

Which one are you referring to by this?

**Comment by minimaluminium** [comment]
The change should be pretty simple if you want to replace the form input with a button. You can replace [this section](https://github.com/TryGhost/Edition/blob/846a09e4a2d1a4ab3ae4c20ba518d02f5a9af0d3/partials/cover.hbs#L20-L28) of `partials/cover.hbs` with:

```hbs
<button class="button" href="#/portal/signup" data-portal="signup">Subscribe</button>
```

Of course, there might be some CSS customization to make it perfect, but will be the right direction.

We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!

**Comment by os72** [comment]
Thanks will do
