### ISSUE TITLE
[Dawn] Code highlighting not working in dark mode

### ISSUE THREAD

**Issue by deanpcmad** [TryGhost/Themes#197]
The text is unreadable

![firefox_MjfPdLX6vg](https://user-images.githubusercontent.com/425200/204781480-1530d331-584f-40fb-8fe6-209f64e5ddce.png)

**Comment by minimaluminium** [comment]
Hey @deanpcmad, thanks for the report!

This is now fixed, make sure re-install the lates copy of the theme for the update.

**Comment by MNeverOff** [comment]
There seems to still be an issue as of Dawn 13.0 with the code snippets

I assume that the order in which the .css files are loaded is incorrect, as this is what I see in my code inspection for `pre` blocks:
<img width="985" alt="SCR-20240204-dcny-2" src="https://github.com/TryGhost/Themes/assets/3989091/68c4404c-4ffb-42cd-bf1f-08ad6efc0564">

It's apparent that there seem to be two variables: `--primary-text-color` and `--color-primary-text`. Whilst the latter would read well in dark mode it's not the one that gets applied. Any advise? For now I'm overriding the `color` property of `pre` HTML elements.
