### ISSUE TITLE
Dawn Theme - Table of Contents (ToC) no longer present or working out of the box

### ISSUE THREAD

**Issue by diliprk** [TryGhost/Themes#199]
I am using the official dawn theme (latest git repo) and looking to set up a ToC as in [this blog website](https://treanches.digitalpress.blog/table-of-contents-ghostblog/#table-of-contents-using-inspect-option-in-browser-) .  I can’t find a `toc-opened class` or even any `toc` class in the [default.hbs](https://github.com/TryGhost/Dawn/blob/main/default.hbs) file . Has the Table of Contents feature been removed in the recent dawn build?

[Official Ghost Tutorial for adding ToC](https://ghost.org/tutorials/adding-table-of-contents) cannot be translated to dawn as the code base for dawn theme is drastically different

**Comment by minimaluminium** [comment]
Hey @diliprk, the TOC feature was removed from Dawn theme intentionally to keep the simple and consistent features across our official themes.

For the official tutorial, this shouldn't be any different for Dawn. The key element for the tutorial is `.gh-content` which contains the post content. It can be found in `partials/content.hbs` partial for Dawn, and the actual piece of code is [here](https://github.com/TryGhost/Dawn/blob/2109eb439ee754c3f4d1e319ca257d486eac48be/partials/content.hbs#L55-L57).

**Comment by d0u9** [comment]
Sad to hear that. TOC and reading progress bar are two most outstanding features Ghost's free theme attacks me.
