### ISSUE TITLE
 Missing Footer Links in new Dawn Theme

### ISSUE THREAD

**Issue by diliprk** [TryGhost/Themes#200]
Hi, 
 I am trying to use the dawn theme which I installed from the ghost dashboard --> Settings --> Design --> Change Theme. At present, the latest dawn theme doesn't seem to be including any interactive links in the footer and I just see a copyright `Blog Name` text and `Published by Ghost` text. I am trying to add the following items to a customized footer.
1.) Github and Linkedin Icons pointing to my respective git and Linkedin profiles
2.) A custom copyright text
3.) Dark/Light Toggle button

For reference, please see the footer on the following two websites:
1.) https://treanches.digitalpress.blog/table-of-contents-ghostblog/ (dark/light theme toggle button)
2.) https://zerodya.net/hello-world/ (Git and Linkedin buttons)

Could someone kindly guide me to where in the `dawn` theme code base I should be adding these custom icons, text and social media URLs and dark/light mode settings?

Best Regards,
Dilip

**Comment by minimaluminium** [comment]
Hey @diliprk,

The secondary navigation is supported in the footer of Dawn theme, which you can add any link in `Settings > Navigaion` on your dashboard. 

If you're looking to add those custom elements, the footer code can be found in `default.hbs` template of the theme. The exact location of the code is [here](https://github.com/TryGhost/Dawn/blob/2109eb439ee754c3f4d1e319ca257d486eac48be/default.hbs#L77-L89).

We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
