### ISSUE TITLE
[Headline] dropdown in gh-head-menu doesn't display

### ISSUE THREAD

**Issue by danajanssen** [TryGhost/Themes#204]
The dropdown button for when the main menu is between full width and hamburger menu doesn't display a dropdown when clicked. Tested in Chrome and Safari.

How to replicate:

1. Visit https://headline.ghost.io/
2. Change browser width to 900px wide so that the main menu dropdown button appears
3. Click the main menu dropdown button
4. No dropdown is visible

![2022-12-20-112445](https://user-images.githubusercontent.com/23863/208739098-ef4b01e5-240a-4f5b-b088-e6294f987ff1.png)

**Comment by markstos** [comment]
I reproduced this today with the HEAD of the `main` branch today in Chromium and Qutebrowser on Linux.

**Comment by danajanssen** [comment]
I can see that his has been fixed, thanks!
