### ISSUE TITLE
[Headline] mobile experience 

### ISSUE THREAD

**Issue by jonwsoto** [TryGhost/Themes#206]
After the [footer optimization ](https://github.com/TryGhost/Themes/commit/b2ecaedb5438cdae1391376c91b0f0d21c5610b4)  was made it has made the mobile experience terrible. 

Visit https://headline.ghost.io/ on your mobile iPhone and scroll down to the footer area. Text doesn’t wrap on edges and it allows you to scroll horizontally which leads to white space where there should be black space. 

![E7205717-8DAC-4BE9-BC7E-19377B97474E](https://user-images.githubusercontent.com/70615150/209248971-ee894895-8a28-42b2-9a9b-81256c30bdd8.png)
![0DD94D38-D320-45F5-BF94-A877392AF307](https://user-images.githubusercontent.com/70615150/209248981-129fdf68-5b33-4b38-9c86-64174813b61b.png)

**Comment by leepish** [comment]
I’m also affected by this when I upgraded to the latest Headline version.

I also noticed that my logo had increased in size.

**Comment by leepish** [comment]
@jonwsoto this has been resolved in later headline versions

**Comment by jonwsoto** [comment]
Ah yes. Let me close. Thank you!
