### ISSUE TITLE
[Headline] Navigation not appearing on `main` branch

### ISSUE THREAD

**Issue by markstos** [TryGhost/Themes#207]
The version of Headline installable through the admin works fine, but today I checked out the `main` branch of headline and did:

 * `yarn`
 * `yarn zip --theme=headline`

And then installed the Zip through the admin area, and the navigation disappeared. No longer changes or theme customizations were made. This happens when the browser width is wide. With the browser is narrow, the navigation doesn't work either, due to:

https://github.com/TryGhost/Themes/issues/204

I spent hours believing there was a bug in my fork before I thought to try to see if I could reproduce the issue on the unmodified version of the theme. 🤦🏼

I suspect it's related to this commit:

https://github.com/TryGhost/Themes/commit/edebeaedbeac827b013637c2e5602b5ffa0bd7e1

Specifically this CSS in `header.css` which is a "shared" asset. I suspect this because the issue is the opacity of the navigation is turned off when it shouldn't be:

```
@media (min-width: 768px) {
    .gh-head-brand .gh-search {
        display: none;
    }

    body:not(.is-dropdown-loaded) .gh-head-menu .nav > li {
        opacity: 0;
    }
}
```

However, CSS and theming isn't my expertise so I'm sure exactly how to fix it.

**Comment by markstos** [comment]
Hmm, I can't reproduce the issue with this zip file:  https://github.com/TryGhost/Headline/archive/main.zip

As far as I can tell, that's being synced from the `main` branch of the Themes repo. So in theory, that should behave the same, right? This points back to something being off in my development environment I suppose. 🤷🏼

**Comment by markstos** [comment]
I'm closing this because I can't reproduce it in the Headline repo.

**Comment by leoxiong** [comment]
Hey @minimaluminium, reopening this issue as I can reproduce the bug on a freshly zip'ed `solo` theme from the latest commit (42f93779fb92b0f7973b39e0cbc1e97eb0395557) on the`main` branch.

It appears that the themes distributed through the Ghost marketplace (and demo pages https://solo.ghost.io/) are still using v1 of the shared JS assets, whereas the latest commit is using v2. Specifically the `dropdown.js` ([v1](https://github.com/TryGhost/Themes/blob/main/packages/_shared/assets/js/v1/lib/dropdown.js#L32), [v2](https://github.com/TryGhost/Themes/blob/main/packages/_shared/assets/js/v2/lib/dropdown.js#L33)) file. In v1 it is adding the `is-dropdown-loaded` class to the `<body>` tag, whereas in v2 it is added to the `<header>` tag. The CSS expects the tag to be on the `<body>` tag.

Seems like it got broken during the v2 migration?

**Comment by leoxiong** [comment]
I did a bit more digging and I think the root cause is the "old package version" selection logic is broken.

The `path` variable is prefixed with `./` but the `oldPackages` list doesn't have it.

You can repro by applying this patch and then running `yarn zip --theme solo`. You'll see it print that the `solo` package is using `v2` instead of `v1`.

```patch
diff --git a/gulpfile.js b/gulpfile.js
index 4e2ec16f..71c71a72 100644
--- a/gulpfile.js
+++ b/gulpfile.js
@@ -54,6 +54,7 @@ function doCSS(path, done) {
 
 function doJS(path, done) {
     const version = oldPackages.includes(path) ? 'v1' : 'v2';
+    console.log(path, version)
     pump([
         src([
             `packages/_shared/assets/js/${version}/lib/**/*.js`,
```

This patch fixed it for me:
```patch
diff --git a/gulpfile.js b/gulpfile.js
index 4e2ec16f..d3b1d042 100644
--- a/gulpfile.js
+++ b/gulpfile.js
@@ -53,7 +53,7 @@ function doCSS(path, done) {
 }
 
 function doJS(path, done) {
-    const version = oldPackages.includes(path) ? 'v1' : 'v2';
+    const version = oldPackages.includes(path.replace(/^.\//, '')) ? 'v1' : 'v2';
     pump([
         src([
             `packages/_shared/assets/js/${version}/lib/**/*.js`,
```

**Comment by minimaluminium** [comment]
Thanks everyone for the reports and feedbacks. Kudos to @leoxiong going the extra mile and fixing the underlying issue 🙂
