### ISSUE TITLE
[Wave] Theme issues

### ISSUE THREAD

**Issue by sfiorucci** [TryGhost/Themes#216]
Hey Ghost Team,

The Wave theme seems to suffer from a couple of severe issues regarding the audio player. They can be reproduced on the demo page too: https://wave.ghost.io/

1. It's quite easy to get the homepage player to work using Facebook Description like [this page](https://wave.ghost.io/about/) says. Clicking on a podcast PLAY button causes the player to pop up on the bottom of the page with another PLAY/PAUSE button, which is fine. The issue is that the button on the pop-up does not respond, although it does allow users to change the playback speed and jump backward/forward. Both of the PLAY/PAUSE buttons on the page should work.

<img width="1034" alt="Screenshot 2023-01-15 at 23 38 05" src="https://user-images.githubusercontent.com/55532244/212725008-414a79e2-e747-41c5-849e-4ab05905b28d.png">

2. On the single podcast page (e.g. [150: It is Podcasts All the Way Down](https://wave.ghost.io/its-podcasts-all-the-way-down/)) the player doesn’t work at all (PLAY/PAUSE button unclickable, no audio played… they look like the exact same issues as the pop-up player in the homepage) making it impossible to play the track from the page.

<img width="1105" alt="Screenshot 2023-01-15 at 23 47 07" src="https://user-images.githubusercontent.com/55532244/212724929-52ff3e04-6c71-4ca7-8a4e-2e2fe7db239c.png">

**Comment by minimaluminium** [comment]
Hey @sfiorucci, sorry about the delay here. Would you be able to reinstall the latest copy of Wave theme? Both the homepage and single post player buttons are working as below.

https://user-images.githubusercontent.com/1418797/221774262-34038e69-58e8-4a45-b54a-e783c008d0bd.mp4
