### ISSUE TITLE
Unable to upload ZIP. 

### ISSUE THREAD

**Issue by GreivinV** [TryGhost/Themes#221]
When downloading the zip, and trying to import, I get the following error message:
I am new and completely ignore how this works, I just wanted to use the themes. Am I doing it wrong?
![2023-02-15_18-33-41](https://user-images.githubusercontent.com/75382817/219218849-2f7dee7e-ea1b-4e7f-acd5-4392084cc19c.png)

**Comment by tmlmt** [comment]
Which theme have you tried to use exactly? The official ghost themes are directly available from the Settings area, where you just need to click on "Use <theme_name>". No need to upload any zip file.

**Comment by minimaluminium** [comment]
Hey @GreivinV, the native comments feature was added in Ghost 5.9.0. If you Ghost site is older than this, try updating Ghost first, then reinstall the theme.
