### ISSUE TITLE
In absence of secondary navigation items on mobile devices, the footer shouldn't include an empty <nav>

### ISSUE THREAD

**Issue by tmlmt** [TryGhost/Themes#225]
Currently, when browsing on a mobile device and there is no secondary navigation items, a `<nav>` element is still being generated, introducing unnecessary associated css features like `padding`s and an extra `gap` (depending on the theme).

It is particularly visible when using [Edge](https://github.com/TryGhost/Edge): 
![image](https://user-images.githubusercontent.com/10244927/220181301-591e5561-4b03-4e70-b148-5c7b681edf6c.png)

Don't know to what extent that applies to other themes (it seems that it doesn't affect Casper for instance), but in the case of Edge, I tend to disagree with the following sentence from the [doc](https://ghost.org/docs/themes/helpers/navigation/#examples):
> The navigation helper doesn’t output anything if there are no navigation items to output, so there’s no need to wrap it in an {{#if}} statement to prevent an empty list.

**Comment by minimaluminium** [comment]
The footer without secondary navigation is now handled better for the official themes including Edge. Thanks for the report!
