### ISSUE TITLE
Theme Ruby ignores the locales/*.json

### ISSUE THREAD

**Issue by KSCNeon** [TryGhost/Themes#227]
I downloaded the current Ruby theme,
created the "locales" folder, created the de.json file for German and entered everything according to your doc, uploaded the theme and changed the language code in the Ghost Settings but the theme is still in English.
I had to rename the .json file to .txt to be able to upload it here, that's not the problem.
[de.txt](https://github.com/TryGhost/Themes/files/10830870/de.txt)

**Comment by minimaluminium** [comment]
Hey @KSCNeon, have you updated your theme files by using the translation helper as mentioned [here](https://ghost.org/docs/themes/helpers/translate/#5-use-the-translation-helper) in the "Use the translation helper" section?

For example, this line of code needs to be updated by using `{{t}}` helper like below to translate the string "You might also like".

```hbs
<span class="text">{{t "You might also like..."}}</span>
```
