### ISSUE TITLE
Change --color-secondary-text to increase contrast

### ISSUE THREAD

**Issue by rachaelfurn** [TryGhost/Themes#23]
By default, the background colour for the Journal theme is #FFF and the secondary text colour is #888, which means things like links and stuff are #888.

Unfortunately #888 foreground on #FFF background fails several accessibility checks for colour contrast, and can be hard/impossible for users to read. The lightest the grey should be to pass all the checks at https://webaim.org/resources/contrastchecker/ and have a contrast high enough for most users to read would be #595959

The file that would need changing is themes/packages/_shared/assets/css/vars.css and it would be the #888 on line 3 that would need updating.

Unfortunately I'm still figuring out how to do the whole pull request thing to submit this change myself, but I thought I'd raise the issue in case anybody else can make this change faster, or tell me to wind my neck in and not make the change at all. 

The main benefit of making this change in the theme files to begin with is that the change will then go out to everyone who uses the theme from now on. And on a personal level, I'm using the basic $11 Ghost Pro which means I can only use their official themes, which means my only option for changing this colour to make it more accessible is to update the original files.

**Comment by praveentcom** [comment]
+1

**Comment by minimaluminium** [comment]
Hey @rachaelfurn, thanks for raising this, and sorry about the delay! 🙂

The secondary text color was updated to #757575 which passes AA standard. #595959 is for AAA which applies to longer form articles that will be read for a significant period of time, which secondary text color wasn't used for.

Just FYI in case if you'll need in the future, the colors can also be overridden in "Settings > Code injection > Site Header" without making changes to theme files. e.g.

```html
<style>
  :root {
    --color-secondary-text: #595959;
  }
</style>
```
