### ISSUE TITLE
Option to hide/show read time as custom config

### ISSUE THREAD

**Issue by leoxiong** [TryGhost/Themes#232]
Hey, would you accept a PR that adds a [custom config option](https://github.com/TryGhost/Themes/blob/main/packages/alto/package.json#L44) that hide/show read times on posts?

**Comment by minimaluminium** [comment]
Hey @leoxiong, we usually try to reserve the custom theme settings for settings that could have high design impact with potential to make publications easy to express their branding. At the moment, we're not planning to add a toggle for this. Thanks for your interest 🙂
