### ISSUE TITLE
Headline theme not displaying properly on iPhone

### ISSUE THREAD

**Issue by ShadowsSide** [TryGhost/Themes#242]
Headline theme not displaying properly on iPhone, whether it is Safari, Edge, or Chrome

![image](https://user-images.githubusercontent.com/61958350/234291523-757509d0-ab9e-4a98-8653-466b03b2b649.png)
![image](https://user-images.githubusercontent.com/61958350/234291557-794874b8-c550-4b94-bca4-5348ed19bb97.png)

**Comment by ShadowsSide** [comment]
iPhone12 pro max , iOS 16.3.1
iPhone SE 3, iOS 16.3

**Comment by hdirect** [comment]
Also having same issue on iPhone 14 pro max. Another area is the author on post page (attached). Any quick fixes? :)
![Uploading 5E4948B2-3721-4B32-9713-0FBF2D4F792D.png…]()

**Comment by hdirect** [comment]
Image: ![E00FDD47-87B4-401C-9944-C33470713E49](https://user-images.githubusercontent.com/111862578/234673449-15f7edfd-b570-45fb-8550-15b645359a27.png)

**Comment by diva-D** [comment]
I'm using the "Solo" theme and have noticed the Author image is not being positioned correctly on the post page

![2023-04-27_11-47-48_SigmaOS_SigmaOS](https://user-images.githubusercontent.com/28694272/234726124-6792caa1-8cbf-43c9-b58c-84f9942cc76a.png)

Seems to be connected to this issue.

**Comment by alnevarez** [comment]
having same both issues on iphone and ipad.. .. the author section overlaps the headline, and skinny post text if there's an image atop the post.   it may be fine on android but good to check.

**Comment by hdirect** [comment]
Has anyone found a temporary fix for this via code inject? Quite a big one for us as mobile is majority of our traffic

Hugo Cannon
CEO

The Direct | Growth Advisory
85 Great Portland Street, First Floor, London, United Kingdom, W1W 7LT
Tel: +44 7741 272842

**Comment by diva-D** [comment]
@hdirect I ended changing my theme in the end (just starting so not a big deal)  but playing around with the CSS I came up with the following:
```html
<style>
    .gh-content .gh-article-header {
        margin-bottom: 15px;
    }
    
    .gh-article-meta {
        grid-row-start: 2;
    }
</style>
```
**NOTE**: this was for the "Solo" theme so unsure how it would transfer to other themes.

The most important bit is the `grid-row-start: 2` line that moves the author data below the title. You can play around with margins as needed until a proper fix is implemented.

You would inject this in Settings > Code injection > Site Header

**Comment by minimaluminium** [comment]
Hey everyone, this is now fixed! The issue was related with the new media query syntax, and it's now reverted.
