### ISSUE TITLE
"Headline" theme - tables are highly condensed

### ISSUE THREAD

**Issue by kisamoto** [TryGhost/Themes#250]
Trying to use Markdown or HTML tables in the "headline" theme results in highly condensed content (see screenshot). 

It's not immediately obvious what styles to change to fix this.

![image](https://github.com/TryGhost/Themes/assets/1744908/3ff29113-654a-480f-ad2b-6a44a59e91ad)

**Comment by minimaluminium** [comment]
Hey @kisamoto, thanks for the report! We've just added proper table styling to all our official themes. The updates will be applied once you re-install the theme.

**Comment by kisamoto** [comment]
Amazing work @minimaluminium - thanks a lot! I'll test it out.

**Comment by kisamoto** [comment]
Can confirm they now have X overflow with scrollbar (screenshot attached). 

![image](https://github.com/TryGhost/Themes/assets/1744908/6351e317-a99b-4407-8b2a-fa3f79b2cbd7)

**Comment by minimaluminium** [comment]
Yeah, tables are complicated when it comes to responsive styling. This is the approach we use for Casper for better readability and usability, and it's now consistent across all themes.

**Comment by kisamoto** [comment]
@minimaluminium 
Is it possible to remove the linear gradient for tables that don't overflow?

![image](https://github.com/TryGhost/Themes/assets/1744908/93abcb72-570e-49f6-9bfa-7f19f03d11a8)

**Comment by minimaluminium** [comment]
@kisamoto This should definitely be fixed, will work on it!
