### ISSUE TITLE
Alto theme with dark mode has a white rectangle in the hamburger menu

### ISSUE THREAD

**Issue by shinomory** [TryGhost/Themes#261]
Ghost Pro install, tested in Chrome on Android, as well as in mobile devmode on desktop Chrome on Windows.

With dark mode enabled and using a mobile browser, at the bottom of the hamburger menu there's a white rectangle behind "Subscribe" that hides the "Sign in" link and looks out-of-place. I think it's a CSS issue with how the theme is built?

For `.is-head-open #gh-head .gh-head-actions`, there's a `background-color: var(--color-white)` sneaking in from somewhere, I'm in way over my head with CSS/building it and didn't try that route.

I was unable to fix the issue with style injection on my Ghost Pro install, so I edited the \built\screen.css directly by changing the var in `.gh-head-actions{align-items:center;background-color:var(--color-white);` to `--dark-mode-bg-color` which is what I think was intended.

It looks like in Alto/assets/css/misc/dark.css the issue was partially fixed for `.dark-mode .off-canvas` but not for `.dark-mode .gh-head` ? Over my head, like I said.

Hopefully this helps someone! I'll email a quick support query on Monday.

**Comment by minimaluminium** [comment]
Hey @shinomory, sorry about the big delay here. The issue has just been fixed. You can re-install the theme to get the fix applied to your site.
