### ISSUE TITLE
phantom cover arrow in Edition Theme

### ISSUE THREAD

**Issue by mlantin** [TryGhost/Themes#265]
In the Edition theme, there is a button with style "cover-arrow" that is created in the cover.hbs partial. It's got an absolute position and is white so if the site bg is white, it randomly occludes text with a kind of white shadow artifact. It's function is to put the "latest posts" section in scroll view but it is invisible and randomly placed. It can safely be taken out I think (as well as some code in main.js that references it).

**Comment by minimaluminium** [comment]
Hey, you're right! The issue has just been fixed in https://github.com/TryGhost/Edition/commit/9401bbbdd155601496faef5cf122f4a1deb24624. Try re-installing the theme to get the update 🙂
