### ISSUE TITLE
Themes lack documentation

### ISSUE THREAD

**Issue by derek-adair** [TryGhost/Themes#272]
Originally I submitted #266 because I was very confused about your shared theme resources and where some of the styles I wanted to change where coming from.  This issue is more succinct and addresses a bigger need here; **The missing documentation for this code.**

-----------
I would really love to see something detailed on how these themes work, something like the [minimal mistakes documentation](https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/).  This would be a boon for developers looking to extend and customize these very pleasantly designed themes.  The css/html is quite pleasant and well made it's just a lot to step in to.

**Comment by minimaluminium** [comment]
TryGhost/Themes is a monorepo that contains all official themes except Casper, and only intended for internal theme development. All changes made in the monorepo are synced automatically with the sub-repos. For example, when there's a change in `packages/dawn`, [TryGhost/Dawn](https://github.com/TryGhost/Dawn) will be updated automatically. 

If you're looking to fork a theme and customize, go to a specific theme's repo ([TryGhost/Dawn](https://github.com/TryGhost/Dawn) as an example) and fork it to add your changes. The instructions for getting started is pretty straightforward - can be found in their own repos, and same for all our official themes.

**Comment by derek-adair** [comment]
>TryGhost/Themes is a monorepo that contains all official themes except Casper, and only intended for internal theme development. 

*document this*

>If you're looking to fork a theme and customize, go to a specific theme's repo ([TryGhost/Dawn](https://github.com/TryGhost/Dawn) as an example) and fork it to add your changes.

*document this*

>the instructions for getting started is pretty straightforward

*except for how/what this monorepo is and how to fork it?*  There are explicit instructions on how to develop against this repository yet i'm told to fork the individual repos in an issue like this -- which I originally did -- only to find `@tryghost/shared-theme-assets` css assets.  Problem is, there is NO mention of where this code lives or how to modify it in the individual themes and the npm listing does not link to this repository.  

--------------

**This code needs documentation, this issue is not complete.**  If the leaders at ghost are wondering why their official theme repo has 20 contributors compared to over 500 on the main repo look no further than the lack of instructions on how to do so paired with convoluted code base organization.

good luck!  You lost me as a contributor on this one -- i love me writing some docs -- although it doesn't seem a welcoming corner to contribute to ghost anyways.
