### ISSUE TITLE
Music Player play button is always black

### ISSUE THREAD

**Issue by behoyh** [TryGhost/Themes#275]
For the solo theme, the play button is always black on chromium / blink based browsers. If the background is also black this will hide the play button from the user.,

**Comment by minimaluminium** [comment]
Hey @behoyh, thanks for your feedback. This issue has been fixed in https://github.com/TryGhost/Themes/commit/2021541d18e203fa30fb3ed153a8bdda27055686. Make sure re-install your theme to get the fixes applied to your site.
