### ISSUE TITLE
Dawn: Usage of {{meta_description}} in HTML head is no longer required

### ISSUE THREAD

**Issue by ghost** [TryGhost/Themes#278]
I recently installed the latest version of Dawn and received the following theme error in my Ghost admin. I have not made any custom tweaks to the theme files - I've only made changes via code injection and the routes file.

![dawn-theme-errors](https://github.com/TryGhost/Themes/assets/136092545/a882d712-12e5-406d-9dc7-2a06f8d09a70)

**Comment by minimaluminium** [comment]
Hey @halphalp,

Can I ask how you installed the theme? We don't have any `{{meta_description}}` in any of our themes, and wondering if you might have installed a customized version.
