### ISSUE TITLE
Plain text view

### ISSUE THREAD

**Issue by mallory** [TryGhost/Themes#325]
It appears that most Ghost themes aren't well designed for plain text views of email messages. I would suggest adding an option in composition of the post to modify the plain text rendering.

For example, the last post I sent was also sent as a newsletter and it added a ton of whitespace to the top of the post, such that my readers who read in plain text thought that the edition was empty. It wasn't, but one had to scroll and scroll in order to get to the body of the post.

I could have fixed this had I been able to see and modify the plain text version of my post before sending. Some other newsletter software allows for this.

Thanks for considering this feature.

**Comment by cathysarisky** [comment]
This is not a theme issue.  Themes don't control email display.  You might want to raise the issue over on the main Ghost repository instead.

**Comment by mallory** [comment]
I would be curious what is being passed from the theme to the core and how that's being interpreted to create plain text. 

Another way to ask this question: do all themes have the same result?

**Comment by cathysarisky** [comment]
Themes have zero to do with email rendering.  They only control how the post/newsletter looks on the website.  So yes, if you've got a problem with plaintext, it's going to be throughout, not theme-specific.

If you'd like to discuss further, head on over to https://forum.ghost.org - issues aren't really the right place.

If you'd like to report a specific email bug related to plain text, please report it against Ghost, not against Themes. :)  Images and details about what mail client showed the problem would be helpful.

**Comment by mallory** [comment]
Ok I opened a new issue here: https://github.com/TryGhost/Ghost/issues/20015
