### ISSUE TITLE
A browser back issue caused by the .gh-subsribe component

### ISSUE THREAD

**Issue by Pathsis** [TryGhost/Themes#54]
### Issue Summary

Once  open`.gh-subsribe`, it keeps **popping up** when the browser goes **BACK**.

I show this problem in the demo of the official Journal theme. I have this problem on my own website.

![2021-11-21_02-23-57 (1)](https://user-images.githubusercontent.com/72077265/142737277-c24b9c91-7145-44bf-a6b0-1c307130522f.gif)

### Steps to Reproduce

1. open `.gh-subsribe`； 
2.  the browser goes back；
3. `.gh-subsribe` keeps popping up.

### Ghost Version

4.22.4

### Node.js Version

v14.18.1

### How did you install Ghost?

Command line installation on Ubuntu 20.04

### Database type

MySQL 8

### Browser & OS version

chrome 95.0.4638.69 (arm 64)

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by Pathsis** [comment]
> 

Thank you for your attention! I presented this problem in a demo of the journal theme on Ghost's official website. I didn't customize the theme, so that you wouldn't think it was my problem. I remember a few updates ago when this problem didn't exist.

> Hey @Pathsis 👋🏼
> 
> This is expected behaviour when you use Portal links to open Portal. If you want to avoid this in a custom theme, you can use the data-attributes method of opening Portal instead of links.
> 
> We'll look into updating our official themes to use the most relevant method to avoid this unexpected behaviour.

Hey @matthanley Thank you for your attention! I presented this problem in the demo of the journal theme on Ghost's **official** website. I didn't customize the theme, so that you wouldn't think it was my problem. I remember a few updates ago when this problem didn't exist.

**Comment by Pathsis** [comment]
> Hey @Pathsis 👋🏼
> 
> This is expected behaviour when you use Portal links to open Portal. If you want to avoid this in a custom theme, you can use the data-attributes method of opening Portal instead of links.
> 
> We'll look into updating our official themes to use the most relevant method to avoid this unexpected behaviour.

Hey @matthanley Thank you for your attention! I didn't customize the theme, I showed the problem in the journal theme demo on Ghost's official website to avoid being mistaken for my own problem. I remember a few updates ago when this problem didn't exist.

**Comment by minimaluminium** [comment]
Hey @Pathsis, this is now fixed in https://github.com/TryGhost/Themes/commit/1cbfb680c3ba5bc575d5a92f2a5e36bcde5ab57a by using data attributes instead of links. Thanks for raising this!

**Comment by Pathsis** [comment]
> Hey @Pathsis, this is now fixed in [1cbfb68](https://github.com/TryGhost/Themes/commit/1cbfb680c3ba5bc575d5a92f2a5e36bcde5ab57a) by using data attributes instead of links. Thanks for raising this!

Appreciate it!
