### ISSUE TITLE
Newsletter form field sidebar

### ISSUE THREAD

**Issue by uxai** [TryGhost/Themes#61]
Can we get thr newsletter form to work without faking readers out on the input field?

**Comment by matthanley** [comment]
Hey 👋 We ask that you please do not use GitHub for help or support 😄. We use GitHub solely for bug-tracking and on-going feature development.

Many questions can be answered by reviewing our documentation. If you can't find an answer then our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
