### ISSUE TITLE
Social media links

### ISSUE THREAD

**Issue by uxai** [TryGhost/Themes#62]
Can we get it so social media links appear in the footer of the page? 

Thanks!

**Comment by matthanley** [comment]
Hey 👋 We ask that you please do not use GitHub for help or support 😄. We use GitHub solely for bug-tracking and on-going feature development.

Many questions can be answered by reviewing our documentation. If you can't find an answer then our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
