### ISSUE TITLE
Using `a` tag with `.gh-btn` under `gh-content` makes text and background the same color.

### ISSUE THREAD

**Issue by yych42** [TryGhost/Themes#66]
This problem is present in Bulletin, but not tested in other themes. See below.

<img width="502" alt="Screen Shot 2021-12-23 at 4 12 48 PM" src="https://user-images.githubusercontent.com/43839115/147301119-b2841558-94bf-412b-ac59-ad76e295f154.png">

<img width="555" alt="Screen Shot 2021-12-23 at 4 13 39 PM" src="https://user-images.githubusercontent.com/43839115/147301155-e96cfb8f-e095-48ca-9151-07464f08604e.png">

**Comment by minimaluminium** [comment]
Hey @yych42, thanks for your report! The issue was fixed in https://github.com/TryGhost/Themes/commit/6a8bb687b028f7b6d0f617e1bdd412b758ad5984, which also fixes the issue in other themes.
